spring: 
  profiles:
    active: dev
  datasource: 
    url: jdbc:mysql://47.112.109.252:3306/yezi?useSSL=false&characterEncoding=utf8
    username: root 
    password: yezi123
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
  resources:
    static-locations: classpath:/resources/,classpath:/static/
  mvc:
    view:
      prefix: /
      suffix: .html
    static-path-pattern: /**
  mail:
    host: smtp.qq.com
    username: 260008747@qq.com
    receivers: 1433378045@qq.com;weiyf_2010@163.com
    password: bvwdymyjolcnbigd
    port: 465
    properties:
      mail:
         smtp:
           socketFactory:
             port: 465
             class: javax.net.ssl.SSLSocketFactory
             fallback: false
    default-encoding: utf-8
  jackson:
    date-format: yyyy-MM-dd HH:mm
    time-zone: GMT+8
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

logging:
  level: {root: INFO, com.wotopten.crm.dao: DEBUG}
